background = 000000
foreground =ffffff
cursor-color = 00ff99
selection-background = 111111
selection-foreground = ffffff

palette = 0=#000000
palette = 1=#ff0055
palette = 2=#00ff99
palette = 3=#ffcc00
palette = 4=#00ccff
palette = 5=#cc00ff
palette = 6=#ff6600
palette = 7=#ffffff
palette = 8=#1a1a1a
palette = 9=#ff0055
palette = 10=#00ff99
palette = 11=#ffcc00
palette = 12=#00ccff
palette = 13=#cc00ff
palette = 14=#ff6600
palette = 15=#f0f0f0
