$bg = #000000
$bg_alt = #111111
$fg = #ffffff
$fg_dim = #666666

$accent_lime = #00ff99
$accent_purple = #cc00ff
$accent_yellow = #ffcc00
$accent_cyan = #00ccff
$accent_pink = #ff0055

general {
    col.active_border = $accent_lime
    col.inactive_border = $bg_alt
}

group {
    col.border_active = $accent_lime
    col.border_inactive = $bg_alt
}

decoration {
    col.shadow = rgba(000000ee)
}

xwayland {
    force_zero_scaling = true
}
