# Hacker Tmux

set -g status-style "bg=#000000,fg=#ffffff"
setw -g window-status-style "fg=#666666"
setw -g window-status-current-style "fg=#00ff99"
set -g pane-border-style "fg=#1a1a1a"
set -g pane-active-border-style "fg=#00ff99"
set -g message-style "fg=#ffffff"
set -g message-command-style "fg=#ffffff"
set -g status-left " #S "
set -g status-right ""
setw -g window-status-format " #I:#W "
setw -g window-status-current-format " #I:#W "
