background = 000000
foreground = e6e2d8
cursor-color = 8fb2ff
selection-background = 121212
selection-foreground = e6e2d8

palette = 0=#000000
palette = 1=#ff95a8
palette = 2=#7fd1a0
palette = 3=#a5968b
palette = 4=#8fb2ff
palette = 5=#b39ddb
palette = 6=#6fbfb4
palette = 7=#e6e2d8
palette = 8=#1e1e1e
palette = 9=#ff95a8
palette = 10=#7fd1a0
palette = 11=#a5968b
palette = 12=#8fb2ff
palette = 13=#b39ddb
palette = 14=#6fbfb4
palette = 15=#ffffff
