preload = /home/dpr/.config/.wallpapers/wallhaven-6lkdmq.jpg
wallpaper =, /home/dpr/.config/.wallpapers/wallhaven-6lkdmq.jpg
# preload =/home/dpr/dots/wallpapers/wallhaven-6lkdmq.jpg
# wallpaper =, /home/dpr/dots/wallpapers/wallhaven-6lkdmq.jpg
splash = false
