# preload = /home/dpr/dots/wallpapers/wallhaven-qd6krd.png
preload = /home/dpr/.config/.wallpapers/wallhaven-qd6krd.png
wallpaper = eDP-1,/home/dpr/.config/.wallpapers/wallhaven-qd6krd.png
splash = false
ipc = on
