# Retro Tmux

# set -g status-style "bg=#000000,fg=#CFCBC2"
setw -g window-status-style "fg=#8A8F8C"
setw -g window-status-current-style "fg=#6FA8FF"
set -g pane-border-style "fg=#1a1a1a"
set -g pane-active-border-style "fg=#6FA8FF"
set -g message-style "fg=#CFCBC2"
set -g message-command-style "fg=#CFCBC2"
set -g status-left " #S "
set -g status-right ""
setw -g window-status-format " #I:#W "
setw -g window-status-current-format " #I:#W "
